name: flutter_application_1

description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.6
  firebase_core: ^3.15.0
  cloud_firestore: ^5.6.10
  firebase_auth: ^5.6.1
  intl: ^0.18.0
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/illustration.png
    - assets/data/dummy.json
    - assets/icons/
    - assets/images/qris.png

  fonts:
    - family: chewy
      fonts:
        - asset: assets/fonts/chewy/Chewy-Regular.ttf